# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = eu-west-3
  default_tags {
    tags = { "Environment" : "production", "Terraform" : "true", "TerragruntPath" : "." }
  }
}

terraform {
  required_version = "~>1.3.4"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>4.40.0"
    }
  }
}
