# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fano-terraform-backend"
    dynamodb_table = "fano-terraform-backend"
    encrypt        = true
    key            = "prod/datastores/terraform-aws-rds/terraform.tfstate"
    region         = "eu-west-3"
  }
}
